# Generated by Django 5.2.4 on 2025-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_chartofaccounts_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='is_control_account',
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='is_group_account',
            field=models.BooleanField(default=False, help_text='Group account that contains sub-accounts'),
        ),
    ]
