# Generated by Django 5.2.4 on 2025-07-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_control_account_to_group_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='is_posted',
        ),
    ]
