# Generated by Django 5.2.4 on 2025-07-20 01:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_company_created_by_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinvoice',
            name='party_name',
        ),
        migrations.RemoveField(
            model_name='stockinvoice',
            name='status',
        ),
        migrations.AddField(
            model_name='stockinvoicelineitem',
            name='amount_ex_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount excluding GST', max_digits=15),
        ),
        migrations.AddField(
            model_name='stockinvoicelineitem',
            name='amount_inc_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount including GST', max_digits=15),
        ),
        migrations.AddField(
            model_name='stockinvoicelineitem',
            name='gst_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='GST amount value', max_digits=15),
        ),
        migrations.AddField(
            model_name='stockinvoicelineitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Item serial number', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer'), ('both', 'Both')], default='both', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ntn', models.CharField(blank=True, help_text='National Tax Number', max_length=20, null=True)),
                ('strn', models.CharField(blank=True, help_text='Sales Tax Registration Number', max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='common.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'parties',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockinvoice',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_invoices', to='inventory.party'),
        ),
    ]
