# Generated by Django 5.2.4 on 2025-07-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stockinvoice_party_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinvoice',
            name='party_address',
        ),
        migrations.RemoveField(
            model_name='stockinvoice',
            name='party_contact',
        ),
    ]
