# Generated by Django 5.2.4 on 2025-07-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_party_contact_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinvoicelineitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stockinvoicelineitem',
            name='serial_number',
        ),
    ]
