# Generated by Django 5.2.4 on 2025-07-20 02:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_company_created_by_and_more'),
        ('inventory', '0004_remove_stockinvoicelineitem_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('export', 'Export'), ('import', 'Import'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return'), ('adjustment', 'Stock Adjustment'), ('opening', 'Opening Stock')], max_length=20)),
                ('movement_date', models.DateField()),
                ('reference_number', models.CharField(help_text='Invoice/Document number', max_length=100)),
                ('quantity_in', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Quantity received', max_digits=15)),
                ('quantity_out', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Quantity issued', max_digits=15)),
                ('balance_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Running balance', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Unit cost at transaction', max_digits=15)),
                ('average_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Average cost after transaction', max_digits=15)),
                ('value_in', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value of stock received', max_digits=15)),
                ('value_out', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value of stock issued', max_digits=15)),
                ('balance_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Running balance value', max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_amount_in', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('gst_amount_out', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='common.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='common.financialyear')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockinvoicelineitem')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.party')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements_detailed', to='inventory.product')),
                ('stock_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockinvoice')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['movement_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'product', 'movement_date'], name='stock_movem_company_d69835_idx'), models.Index(fields=['financial_year', 'movement_type'], name='stock_movem_financi_6a69ff_idx'), models.Index(fields=['product', 'movement_date'], name='stock_movem_product_363a5e_idx')],
            },
        ),
    ]
