# Generated by Django 5.2.4 on 2025-07-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='is_current',
        ),
    ]
